version: 2.1
jobs:
  test:
    docker:
      - image: clojure:openjdk-11-lein-2.9.1
    working_directory: /home/circleci/owainlewis/java-http-clj
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: /home/circleci
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: lein deps      
      - save_cache:
          paths:
            - /home/circleci/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - owainlewis/java-http-clj
      # run tests!
      - run: lein with-profiles dev test
  deploy:
    working_directory: /home/circleci/owainlewis/java-http-clj
    docker:
      - image: clojure:openjdk-11-lein-2.9.1
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Deploy to clojars
          command: lein deploy clojars

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
